# Name(s)
Ryan Solorzano

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

N/A

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [ ]:
# YOUR SOLUTION HERE
# a = [[2 for i in range(6)] for i in range(4)]
import numpy as np
a = np.full((6,4), 2)
print(a)

In [5]:
## Exercise 2

In [7]:
# YOUR SOLUTION HERE
b = np.ones((6,4), int)
np.fill_diagonal(b, 3)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 3

In [8]:
# YOUR SOLUTION HERE
# Multiplies each element across the array i.e. A[0,0] is multiplied by B[0,0].
# Not true matrix multiplication
print(a * b)
# Is meant to be true matrix multiplication, and a 6x4 array cannot be
# multiplied by another 6x4 since the number of columns of the first array 
# does not equal the number of rows of the second, so matrix multiplication
# is impossible
# print(np.dot(a, b))

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 4

In [9]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(), b))
print(np.dot(a, b.transpose()))
# The first matrix multiplication multiplies 4x6 matrix with a 6x4 matrix, which results in a 4x4 array
# The second matrix multiplication multiplies a 6x4 matrix with a 4x6 matrix, which results in a 6x6 array
# The difference comes with the nature of matrix multiplication

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [10]:
# YOUR SOLUTION HERE
print("Hello World!")

Hello World!


## Exercise 6

In [11]:
# YOUR SOLUTION HERE
c = np.random.rand(1000) 
d = np.random.randn(1000) 
e = np.random.normal(20, 5, 1000) 
f = np.random.uniform(-100, 100, 1000) 
g = np.random.randint(-10, 20, 1000) 

print("sum", np.sum(c), "mean", np.mean(c), "standard deviation", np.std(c))
print("sum", np.sum(d), "mean", np.mean(d), "standard deviation", np.std(d))
print("sum", np.sum(e), "mean", np.mean(e), "standard deviation", np.std(e))
print("sum", np.sum(f), "mean", np.mean(f), "standard deviation", np.std(f))
print("sum", np.sum(g), "mean", np.mean(g), "standard deviation", np.std(g))

sum 482.997681754773 mean 0.482997681754773 standard deviation 0.28192165569878236
sum 41.26494757045395 mean 0.04126494757045395 standard deviation 0.9864008908458518
sum 20114.90580956635 mean 20.11490580956635 standard deviation 4.880801159908739
sum 2821.0169716188207 mean 2.8210169716188207 standard deviation 57.049258097030894
sum 4631 mean 4.631 standard deviation 8.787766439772964


## Exercise 7

In [12]:
# YOUR SOLUTION HERE
import numpy as np
def count(arr, value):
    count = 0
    for idx in arr:
        count = count + 1 if idx == value else count
    return count

h = np.random.randint(0,1000,10000)
print(count(h, 1))
print(len(np.where(h == 1)[0]))

10
10


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [13]:
# YOUR SOLUTION HERE
import pandas as pd

i = pd.DataFrame(np.full((6,4), 2))
print(i)

   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [14]:
# YOUR SOLUTION HERE
j = pd.DataFrame(np.ones((6,4)))
j.iloc[range(4), range(4)] = 3
j

0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [18]:
# YOUR SOLUTION HERE
print (i * j)
# Below code will throw a ValueError since dimensions don't match
# print (pd.DataFrame.dot(i, j))

     0    1    2    3
0  6.0  2.0  2.0  2.0
1  2.0  6.0  2.0  2.0
2  2.0  2.0  6.0  2.0
3  2.0  2.0  2.0  6.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [45]:
# YOUR SOLUTION HERE
def count(arr, value):
    count = 0
    for idx,rows in arr.iterrows():
        count = count + 1 if rows[0] == value else count
    return count

k = pd.DataFrame(np.random.randint(0,1000,10000))
print(count(k, 1))
print(len(np.where(k == 1)[0]))

11
11


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [66]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [48]:
## YOUR SOLUTION HERE
titanic_df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [67]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex', inplace=True)
titanic_df.loc['female']

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [69]:
## YOUR SOLUTION HERE
titanic_df.reset_index(inplace=True)
titanic_df

index     sex  pclass  survived  \
0         0  female       1         1   
1         1    male       1         1   
2         2  female       1         0   
3         3    male       1         0   
4         4  female       1         0   
...     ...     ...     ...       ...   
1304   1304  female       3         0   
1305   1305  female       3         0   
1306   1306    male       3         0   
1307   1307    male       3         0   
1308   1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 15 columns]